language: csharp
solution: ConsoleApplication1/correlationCalculator.sln
install:
  - nuget restore ConsoleApplication1/correlationCalculator.sln
  - nuget install xunit.runners.console -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ConsoleApplication1/correlationCalculator.sln
  - mono ./testrunner/xunit.runner.console.1.9.2/tools/xunit.console.exe ./ConsoleApplication1/UnitTestProject1/bin/Release/UnitTestProject1.dll
  