language: csharp
script:
  - xbuild /p:Configuration=Debug ConsoleApplication1/correlationCalculator.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ConsoleApplication1/correlationCalculator.sln
after_script:
  - nunit-console ConsoleApplication1/UnitTestProject1/bin/Debug/UnitTestProject1.dll
