language: csharp
solution: ConsoleApplication1/correlationCalculator.sln
script:
  - xbuild /p:Configuration=Release ConsoleApplication1/correlationCalculator.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./ConsoleApplication1/UnitTestProject1/bin/Release/UnitTestProject1.dll
  